// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed img/logo.png
var resourceLogoPngData []byte
var resourceLogoPng = &fyne.StaticResource{
	StaticName:    "img/logo.png",
	StaticContent: resourceLogoPngData,
}
